; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32dev
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
;board_build.partitions = min_spiffs.csv
board_build.partitions = no_ota.csv
board_build.filesystem = spiffs
monitor_speed = 115200
upload_speed = 921600
; build_type = debug

lib_deps =
    fastled/FastLED @ ^3.6.0
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    earlephilhower/ESP8266Audio @ ^1.9.7
	bblanchon/ArduinoJson @ ^6.21.0
	https://github.com/pschatzmann/arduino-audio-tools.git
	arduinogetstarted/ezButton @ ^1.0.4

monitor_filters = esp32_exception_decoder
; Set optimization level and amount of debug information generated by the compiler
;debug_build_flags = -O0 -ggdb3 -g3